vars: {
  d2-config: {
    pad: 40
  }
}
style.fill: "#0B1020"
classes: {
  svc: {style: {fill: "#131B30"; stroke: "#5B7CBA"; stroke-width: 2; font-color: "#E6EDF7"; border-radius: 10; font: mono}}
  edge: {style: {fill: "#131B30"; stroke: "#4CC9F0"; stroke-width: 2; font-color: "#E6EDF7"; border-radius: 10; font: mono}}
  db: {shape: cylinder; style: {fill: "#131B30"; stroke: "#B388FF"; stroke-width: 2; font-color: "#E6EDF7"; font: mono}}
  state: {shape: circle; style: {fill: "#131B30"; stroke: "#5B7CBA"; stroke-width: 3; font-color: "#E6EDF7"; font: mono}}
}
